<h1 class="title-detail">Ronaldo được khuyên thử thêm vận may với Juventus</h1>
<p class="description">Theo cựu hậu vệ Juventus - Nicola Legrottaglie, Cristiano Ronaldo có thể đoạt Champions League cùng Juventus năm tới.</p>
<article class="fck_detail ">
    <p class="Normal">"Theo hiểu biết của tôi về Cristiano, cậu ấy sẽ không bỏ đi", Nicola Legrottaglie nói với kênh radio <em>Bianconera</em> hôm 12/3. "Cậu ấy sẽ ở lại tới khi đạt mục đích. Cristiano gia nhập Juventus để vô địch Champions League và cậu ấy nên thử ít nhất thêm một năm nữa".</p>
    <figure data-size="true" itemprop="associatedMedia image" itemscope="" itemtype="http://schema.org/ImageObject" class="tplCaption action_thumb_added">
        <div class="action_thumb flexbox" style="z-index: 9; transform-origin: 0px 0px; opacity: 1; transform: scale(1, 1); display: none;">
            <a href="javascript:;" class="share_photo" data-type="fb" data-reference-id="31"><svg class="ic ic-facebook"><use xlink:href="#Facebook"></use></svg></a>
            <a href="javascript:;" class="share_photo" data-type="tw" data-reference-id="31"><svg class="ic ic-twitte"><use xlink:href="#Twitter"></use></svg></a>
            <a href="javascript:;" class="vne_zoom" style="transform-origin: 0px 0px; opacity: 1; transform: scale(1, 1);"><svg class="ic ic-zoom"><use xlink:href="#Zoom"></use></svg></a>
        </div>
        <meta itemprop="url" content="https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=0&amp;h=0&amp;q=100&amp;dpr=2&amp;fit=crop&amp;s=WJwICgaogGiZqqr45ktTZA">
        <meta itemprop="width" content="1200">
        <meta itemprop="height" content="800">
        <meta itemprop="href" content="">
        <div class="fig-picture" style="padding-bottom: 66.666666666667%;position: relative;"><picture data-inimage="done">
                <!--[if IE 9]><video style="display: none;"><![endif]-->
                <source data-srcset="https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Z4CXmLUICNkeU3IGEcEsgA 1x, https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=1020&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Qmjbj-KVJ4ktD1cFWI9XeA 1.5x, https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=2&amp;fit=crop&amp;s=DxHHE4U7iywjqUkfFJKKEQ 2x" srcset="https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Z4CXmLUICNkeU3IGEcEsgA 1x, https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=1020&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Qmjbj-KVJ4ktD1cFWI9XeA 1.5x, https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=2&amp;fit=crop&amp;s=DxHHE4U7iywjqUkfFJKKEQ 2x">
                <!--[if IE 9]></video><![endif]-->
                <img itemprop="contentUrl" style="position: absolute;width:100%;left:0;" loading="lazy" intrinsicsize="680x0" alt="Ronaldo đã đoạt hai danh hiệu Serie A và hai danh hiệu Siêu cúp Italy cùng Juventus. Ảnh: Goal." class="lazy lazied" src="https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Z4CXmLUICNkeU3IGEcEsgA" data-src="https://i1-thethao.vnecdn.net/2021/03/13/2-9464-1615595939.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=Z4CXmLUICNkeU3IGEcEsgA" data-ll-status="loaded">
                <div class="embed-container" style="display:block;position:absolute;width:100%;height:100px;padding-bottom:0px !important;margin-bottom:0px !important;bottom:-1px;"><style>#sis_inimage{position:relative;width:100%;height:100%;}</style><div id="sis_inimage" data-google-query-id="CIzZmMKUre8CFU_OvQodFWQPbA" style="text-align: center;"><div id="google_ads_iframe_/27973503/Vnexpress/Desktop/Inimage/Thethao/Thethao.bongda.detail_0__container__" style="border: 0pt none;"><iframe id="google_ads_iframe_/27973503/Vnexpress/Desktop/Inimage/Thethao/Thethao.bongda.detail_0" title="3rd party ad content" name="google_ads_iframe_/27973503/Vnexpress/Desktop/Inimage/Thethao/Thethao.bongda.detail_0" width="1" height="1" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" srcdoc="" style="border: 0px; vertical-align: bottom;" data-google-container-id="4" data-load-complete="true"></iframe></div></div></div></picture></div>
        <figcaption itemprop="description">
            <p class="Image">Ronaldo đã đoạt hai danh hiệu Serie A và hai danh hiệu Siêu cúp Italy cùng Juventus. Ảnh: <em>Goal</em>.</p>
        </figcaption>
    </figure>
    <p class="Normal"><a href="https://vnexpress.net/chu-de/cristiano-ronaldo-194" rel="dofollow">Cristiano Ronaldo</a> gia nhập Juventus hè 2018 và ngay lập tức đoạt Scudetto. Tuy nhiên, tại Champions League, anh và đồng đội liên tiếp dừng bước sớm ba mùa vừa qua. Hợp đồng của siêu sao Bồ Đào Nha với <a href="https://vnexpress.net/chu-de/juventus-132" rel="dofollow">Juventus </a>còn đến tháng 6/2022 và đôi bên chưa bàn chuyện gia hạn.</p><p class="Normal">"Cristiano chơi tệ trước Porto và hứng chịu nhiều chỉ trích. Nhưng cậu ấy sẽ không bỏ cuộc", Legrottaglie nói thêm về thất bại của Ronaldo và Juventus mùa này. "Cậu ấy muốn nhận trách nhiệm và sẽ thử thêm một mùa giải nữa. Các CĐV có quyền cho rằng Juventus đã thụt lùi so với các đội bóng lớn ở châu Âu. Nỗi thất vọng lúc này không chỉ là Juventus bị loại mà vì họ thua Porto, đội bóng không thuộc hàng đại gia. Cần làm rõ vì sao một CLB như Juventus lại để thua ở vòng 1/8 trước Porto".</p><p class="Normal">Ronaldo ghi 92 bàn sau 121 trận cho Juventus. Nhưng hai mùa gần nhất ở <a href="https://vnexpress.net/chu-de/champions-league-506" rel="dofollow">Champions League</a>, anh chỉ ghi tổng cộng tám bàn. Sau khi bị Porto loại, CEO Juventus – Fabio Paratici khẳng định gia hạn hợp đồng với Ronaldo <a href="https://vnexpress.net/juventus-chua-voi-gia-han-voi-ronaldo-4246172.html" rel="dofollow">không phải việc cấp bách</a> của đội bóng thành Turin.</p><p class="Normal">"Juventus vẫn cần Cristiano ở Champions League", Legrottaglie khẳng định. "Họ khó vô địch châu Âu nếu thiếu một chân sút tầm cỡ như Cristiano. Việc Juventus phải làm là cải thiện hệ thống phòng ngự. Một số bàn thua của họ ở Champions League là những sai lầm tai hại. Họ nên tập trung cải thiện hàng thủ, thay vì nghĩ đến chuyện làm mới hàng công".</p>
    <p class="Normal" style="text-align:right;"><strong>Vy Anh</strong> (theo <em>Goal</em>)</p>
</article>